### PR TITLE
Adding TypeScript declarations file.

### PR DESCRIPTION
**Pull request by mrf345**
#### Problem:
- The component is missing a TypeScript declaration file
definition_error

#### Solution:
- Add a declaration file `index.d.ts`
define_fix

##### Note:
- I didn't add [`filterOptions` ](https://github.com/tbleckert/react-select-search#configuration) since i wasn't able to find any mention of it anywhere in the code-base except in the `README.md`. [Search Results](https://github.com/tbleckert/react-select-search/search?q=filterOptions&unscoped_q=filterOptions).
- I've set some of `renderValue` parameters to type `any` since i wasn't able to get the function to fire so i can inspect and map it's values accurately.

#### Related issues:
#68 

<hr />

Thanks so much for the awesome component ✨

### CODE REVIEW

**Comment by tbleckert** [comment]
@mrf345 Thank you, this is awesome. Will test it out today.

**Comment by mrf345** [comment]
Awesome, thanks for taking a look.

**Comment by tbleckert** [comment]
@mrf345 I've tested it now, sorry for the delay. A few things:

* The onChange arguments are: selectedValue and selectedOption. Both of them are arrays if multiple is true.
* The renderOption callback receives: domProps, option, snapshot and className. Snapshot is an object containing two booleans; selected and highlighted.
* The renderValue callback receives: valueProps, snapshot, className. The snapshot is the same object returned by the useSelect hook.
* A few missing props that came after you submitted this.

Otherwise works fine, great work!

**Comment by mrf345** [comment]
Hi @tbleckert , No worries and thanks for the well detailed remarks.

I've just  fixed the exiting types, and added the ones that came after. Please let me know if i've missed any remark.

**Comment by tbleckert** [comment]
@mrf345 Nice, great work. I'll merge it in and include it in the next release

**Comment by feimosi** [comment]
These types are not compatible for me (latest TypeScript). Based on the errors I was getting, `DomProps` should look like this:

```ts
  export type DomProps = {
      tabIndex:number
      onMouseDown:(event:MouseEvent<HTMLButtonElement>) => void
      onKeyDown:(event:KeyboardEvent<HTMLButtonElement>) => void
      onKeyPress:(event:KeyboardEvent<HTMLButtonElement>) => void
      onBlur:(event:FocusEvent<HTMLButtonElement>) => void
      value:string
      disabled:boolean
  }
```

I'm new to this library and don't know all the options,`HTMLButtonElement` should probably be generic.

**Pull request merged**
