### PR TITLE
fix issue #140

### PR DESCRIPTION
**Pull request by chuksjoe**
When setting the initial value of a multiple select input to an array of values, it usually an error.
This PR fixes that error.

### CODE REVIEW

**Comment by tbleckert** [comment]
Thanks for the fix @chuksjoe ! I think it might be worth exploring why undefined values reaches getDisplayValue in the first place. I think the real error comes earlier in the chain. Haven't looked into it yet but I think `getNewValue` might be a good start.

**Comment by tbleckert** [comment]
@chuksjoe Looks like we exit early if no old value, but doesn't handle arrays here https://github.com/tbleckert/react-select-search/blob/master/src/lib/getNewValue.js#L7 . Should be something like:

```js
if (!oldValue) {
    return !Array.isArray(value) ? [value] : value;
}
```

**Comment by chuksjoe** [comment]
At the point where it checks the initial values against the `options` if the `options` is not gotten immediately (that is if the options list is dependent on an API call), the values in the list will be `undefined` and trying to get the name in `getDisplayValue()` will fail. So checking if the value exists (`singleOption && singleOption.name`) helps prevent the whole code from breaking.

**Comment by tbleckert** [comment]
@chuksjoe Yes, I just meant that falsy values shouldn't even be in the array and reach `getDisplayValue`. So the fix is more a patch. For example, the `getOption` produces falsy values and sends those to `getDisplayValue` (https://github.com/tbleckert/react-select-search/blob/master/src/useSelect.js#L51-L61).

This has been refactored quite a bit in the `next` branch. So the fix is only needed in `getNewValue`, sorry for the confusion, got a bit ahead of myself.

But let's merge this in and publish as this fixes the issue for now.

**Comment by chuksjoe** [comment]
Yea. that's great. Thanks

**Pull request merged**
