### PR TITLE
Fixed issue with selecting value async section after search

### PR DESCRIPTION
**Pull request by tarun1081998**
I have reported a bug, I was able to fix that please take a look

### CODE REVIEW

**Comment by tarun1081998** [comment]
https://github.com/tbleckert/react-select-search/issues/260
this PR is addressing the above mentioned issue
@tbleckert

**Comment by mateusz-michalski** [comment]
Can this be merged? I want to use it in my project with async options but without this functionality it is useless

**Comment by tarun1081998** [comment]
@tbleckert can you checkout this PR for issue https://github.com/tbleckert/react-select-search/issues/260

**Comment by youngnic** [comment]
If you are not using async option then this bug fix is problematic. In the past when I entered a search value the search value was cleared, now that doesn't happen so next time I try a new search I have to delete the old value.

**Pull request merged**
