### PR TITLE
Added Jest tests and able to turning off search field in multiselect

### PR DESCRIPTION
**Pull request by coxdn**
extend-examples

jest-tests

### CODE REVIEW

**Comment by tbleckert** [comment]
Wow, this is a lot of work, thank you! I'll go through everything today and merge it in ASAP. Just out of curiosity, is there any particular reason you prefer Jest over AVA?

Really appreciate your work!

**Comment by coxdn** [comment]
In AVA, I did not find the ability to group tests. And I could not figure out how to display the code coverage ⊙︿⊙
Otherwise, of course, they all look the same. At first, I honestly tried to do everything on AVA)

**Comment by tbleckert** [comment]
Ah nice. I usually go with Jest but decided to give AVA a try on a few projects.

Anyways this seems to be working as expected. Altough the tests fails in my end in the selectSearch test. But Travis seems to make it work so probably just something on my end.

**Comment by coxdn** [comment]
Could you show the error that the test run displays?

**Comment by tbleckert** [comment]
@coxdn It worked after I deleted yarn.lock and updated all dependencies. So probably something that was out of date. A dependency updated was due either way. Works like a charm now and I also added coveralls to Travis.

**Pull request merged**
